### PR TITLE
fix(dynamite_end_to_end_test): fix spec validity

### PR DESCRIPTION
**Pull request by Leptopoda**
another issue #1131 could have caught

### CODE REVIEW

**Review by provokateurin — COMMENTED** [review]
I don't understand why it was not valid?

**Comment by Leptopoda** [comment]
oneOf is not an object.
Or am I wrong?

**Comment by provokateurin** [comment]
I assumed that is valid as long as the objects inside oneOf are objects, but I might be wrong. Can you check what exactly the spec says?

**Comment by Leptopoda** [comment]
I could not find any definitive answer.
The openapi-generator happily validates #1098 so we can't trust it either.

**Comment by provokateurin** [comment]
Then I'd say we can support this, as long as the entries inside the nested someOfs are all objects.

**Comment by Leptopoda** [comment]
Closing this for now.
Let's continue the discussion over at #1131

**Pull request closed without merging**
