### PR TITLE
chore(tool): Disable custom_lint

### PR DESCRIPTION
**Pull request by provokateurin**
https://github.com/invertase/dart_custom_lint/issues/261 prevents us to upgrade to Dart 3.5/Flutter 3.24.
Once fixed this commit can be reverted.

### CODE REVIEW

**Comment by provokateurin** [comment]
I updated https://github.com/nextcloud/neon/pull/2360 to ensure it will work

**Review by Leptopoda — APPROVED** [review]
LGTM, but wouldn't it be enough to disable the analyzer plugin and `custom_lint` dependency?

`neon_lints` would still depend on `custom_lint_builder`, but the functionality wouldn't be exported. That way we would avoid commenting out all the dart files.

**Comment by provokateurin** [comment]
I'll check it

**Comment by provokateurin** [comment]
I added it to https://github.com/nextcloud/neon/pull/2360 to ensure I properly disabled it now and it will work with Dart 3.5.

**Comment by provokateurin** [comment]
For the record:
```
ERROR: /home/runner/.pub-cache/hosted/pub.dev/custom_lint_builder-0.6.4/lib/src/client.dart:46:1: Error: 'LintCode' is imported from both 'package:analyzer/src/dart/error/lint_codes.dart' and 'package:custom_lint_core/src/lint_codes.dart'.
```
So the custom_lint_builder dependency in neon_lints has to go too.

**Pull request closed without merging**
