### PR TITLE
Fix/dynamite conflicting variables

### PR DESCRIPTION
**Pull request by provokateurin**
Fixes https://github.com/nextcloud/neon/issues/572

### CODE REVIEW

**Comment by provokateurin** [comment]
@Leptopoda do you know what the best way is for creating tests for a build_runner? i would like to add a spec that intentionally uses the internal variable names as parameters to validate that correct code is generated.

**Comment by Leptopoda** [comment]
I don't know nut iirc when I contributed to built_value they just have a example file in the test dir and let the build_runner run.

This would mean just adding a spec into the test folder and generating a client but maybe there is a better way :shrug:

**Comment by provokateurin** [comment]
There is https://github.com/google/json_serializable.dart/blob/master/json_serializable/test/ensure_build_test.dart which seems to just build the example and check that the code is working. I will try to implement that as well

**Comment by provokateurin** [comment]
Bleh it's not that easy, I would just like to fix this now

**Review by Leptopoda — APPROVED** [review]

**Pull request merged**
