### PR TITLE
feat(neon_http_client): add csrf interceptor 

### PR DESCRIPTION
**Pull request by Leptopoda**
The coverage is a bit different from the one reported by the `flutter_test` package, as they both use different coverage collectors.

Let's hope it won't be too off from the current one

### CODE REVIEW

**Comment by provokateurin** [comment]
Wasn't there a reason why we used flutter for running tests to collect coverage? I remember something wasn't working, but can't find the PR anymore.

**Review by provokateurin — APPROVED** [review]
Works as expected, but please check my last comment before merging.

**Comment by Leptopoda** [comment]
The way we collected the coverage before was broken and I think that you mainly wanted to unify both test cases.
 https://github.com/nextcloud/neon/pull/1858
 
 what do you think?

**Comment by provokateurin** [comment]
Please break the tests on purpose to ensure the job will fail, since that was one of the problems we had before

**Comment by provokateurin** [comment]
Thanks for the test, seems like the CI will still fail properly :+1:

**Pull request merged**
