### PR TITLE
feat(dynamite): Support decoding booleans

### PR DESCRIPTION
**Pull request by provokateurin**

### CODE REVIEW

**Comment by Leptopoda** [comment]
Is this something we need immediately or just a nice to have?

As this isn't really openapi conformant I'd like to have this behind an option or specify custom types (see #749). In that case let's talk about it next week.

**Comment by provokateurin** [comment]
I had this problem with the generated Talk spec, I don't remember exactly in what context this occurred 😅

**Comment by provokateurin** [comment]
I remember what this was used for: Booleans in headers
We now have the problem that this is also present in the core of Nextcloud server, so we need to support this in some way.
As far as I can tell this has to be fully supported since headers are just a normal OpenAPI schema.
I'm not sure how to proceed with this :thinking:

**Comment by provokateurin** [comment]
As far as I can tell this is expected behavior. https://swagger.io/docs/specification/describing-parameters has an example which encodes a boolean as literal `true` and https://github.com/stoplightio/elements (which Nextcloud uses to render the OpenAPI documentation) also does this when sending requests or generating code snippets.
The encoding part doesn't need to be updated because it already works ootb when calling `toString()` on a Dart boolean.

**Review by Leptopoda — APPROVED** [review]
LGTM.
It'll probably be changed a bit with the DynamiteRawResponse

**Pull request merged**
