### PR TITLE
feat(tool): Configure renovate groups

### PR DESCRIPTION
**Pull request by provokateurin**
Closes https://github.com/nextcloud/neon/issues/828

### CODE REVIEW

**Review by Leptopoda — COMMENTED** [review]
👍 
Once we publish our packages dynamite => dynamite_runtime would also be a good candidate.

**Review by Leptopoda — APPROVED** [review]

**Comment by provokateurin** [comment]
Technically yes, but since we use them via local path they never get any updates

**Comment by Leptopoda** [comment]
But the published nextcloud package will need to depend on the published dynamite versions.
Technically dynamite itself doesn't matter as it's a dev dependency but we should make sure they're both in sync.

Maybe melos also does that for us?

**Comment by provokateurin** [comment]
Ah that part you mean. I guess you are right about configuring a renovate group for them

**Pull request merged**
