### PR TITLE
Fix/capabilities

### PR DESCRIPTION
**Pull request by provokateurin**
Fixes https://github.com/nextcloud/neon/issues/586
Depends on https://github.com/nextcloud/server/pull/40001

This now uses anyOf for the capabilities which is a lot better than trying to merge the capabilities manually.

### CODE REVIEW

**Comment by provokateurin** [comment]
@adil192 could you test this to make sure it fixes your problem?

**Review by Leptopoda — APPROVED** [review]
Basically a rebuild with the updated specs isn't it?

**Comment by provokateurin** [comment]
Exactly, just needed some adjustments afterwards.

**Comment by adil192** [comment]
> @adil192 could you test this to make sure it fixes your problem?

Yep!

```dart
final CoreOcsGetCapabilitiesResponse200ApplicationJson_Ocs_Data capabilities;
final bool ncServerIsSupported;
final int ncSupportedVersion;
try {
  capabilities = await client.core.ocs.getCapabilities()
    .then((capabilities) => capabilities.ocs.data);
  (ncServerIsSupported, ncSupportedVersion) = client.core.isSupported(capabilities);
  log.info('ncServerIsSupported: $ncServerIsSupported, ncSupportedVersion: $ncSupportedVersion');
} catch (e) {
  log.severe('Failed to get capabilities', e);
  throw NcLoginFailure();
}
```
```console
flutter: INFO: _NcLoginPageState: ncServerIsSupported: true, ncSupportedVersion: 27
```

**Pull request merged**
