### PR TITLE
feat(nextcloud): test validity of the generated clients

### PR DESCRIPTION
**Pull request by Leptopoda**
implements:  #555

### CODE REVIEW

**Comment by Leptopoda** [comment]
depends on #1024
Looks like the CI liked my changes.

**Comment by Leptopoda** [comment]
This is based on the work we did in #1035

**Review by provokateurin — COMMENTED** [review]
This looks mostly good, but I still don't like that it gets so complex.
I have an idea how we can do this better:

Move the ensure_validity_test.dart files into a source_verification_test/ dir inside the packages.
Then adjust the melos commands to run with concurrency 1 for packages with that dir and point the test command only to that dir.
Of course this makes it a bit more work to run those tests locally for a single package because you now need to run `fvm dart test source_verification_test/`, but I would argue that you rarely want to run those tests locally if not never.
They are really just for the CI to ensure everything committed is up-to-date.

Does this make sense? Maybe I'm still missing something, but in my head this is much better than the tricks with the tags and checking for the specific test file name.

**Comment by provokateurin** [comment]
The other option that gets completely rid of these problems and the build_verify way is to just setup a workflow that runs the generate scripts and checks for diffs with git diff. That would be a more classic approach which might be better because we just avoid this whole mess.

**Comment by Leptopoda** [comment]
> The other option that gets completely rid of these problems and the build_verify way is to just setup a workflow that runs the generate scripts and checks for diffs with git diff. That would be a more classic approach which might be better because we just avoid this whole mess.

Feel free to implement this. I'm not a script wizard as you are :)
I think this approach is completely fine and once we support more platforms we might want to expand the tags even further (thinking about web tests).

Maybe we can just skip the tag entirely in packages that don't use it but I'm not sure this would work.

**Comment by provokateurin** [comment]
Ok I'll do that and open a new PR

**Pull request closed without merging**
