### PR TITLE
generate custom serializers for all classes

### PR DESCRIPTION
**Pull request by Leptopoda**
Depends on #1129
Needed for #1049

### CODE REVIEW

**Comment by Leptopoda** [comment]
In a followup I'll use this in #1054

**Review by provokateurin — COMMENTED** [review]
I'll review once the other PR is merged and this is rebased.

General question: This shouldn't have any performance impact since you are basically just moving code from the .openapi.g.dart file to our .openapi.dart file, right?

**Comment by Leptopoda** [comment]
No performance impact for the users of the package but running the built_value_generator is less performant thus generation might be slower (I think this is due to the analyzer needing to parse bigger files but I haven't looked into this)

**Review by provokateurin — APPROVED** [review]

**Comment by Leptopoda** [comment]
I will wait for the petstore to land so we have more tests.

**Comment by provokateurin** [comment]
I was about to suggest waiting for this and put Petstore on top, but this also makes sense :)

**Comment by provokateurin** [comment]
I think it is easier to merge right now. I'm a bit stuck with the petstore because of https://github.com/nextcloud/neon/pull/1137#issuecomment-1809679423

**Comment by Leptopoda** [comment]
no worries.
I'll at least test it on the petstore branch tomorrow and merge if everything is fine.

**Comment by provokateurin** [comment]
@Leptopoda please rebase

**Review by provokateurin — APPROVED** [review]

**Comment by Leptopoda** [comment]
finally back to our old pace and generating lots of code :tada:

**Pull request merged**
