### PR TITLE
Require Dart ^3.0 and Flutter ^3.22

### PR DESCRIPTION
**Pull request by provokateurin**
Closes https://github.com/nextcloud/neon/issues/2119

### CODE REVIEW

**Comment by provokateurin** [comment]
Not really, but I'd still like to align the requirements because the current state is just a mess.

**Comment by Leptopoda** [comment]
Then let's rather upgrade to dart 3.4 directly as I'd love to play a bit with exension types :P

**Comment by provokateurin** [comment]
Should we really do this? It will force all users of the nc package to upgrade as well (including the upgrade to the latest flutter version if they use it in a flutter project). I'd just wait until it is necessary to have Dart 3.4 for some feature we want to have or use.

**Comment by provokateurin** [comment]
Agreed, so let's downgrade to ^3.0.0 instead?

**Comment by Leptopoda** [comment]
if possible yes.
I don't think we rely on any 3.1 features

**Review by Leptopoda — APPROVED** [review]

**Pull request merged**
