### PR TITLE
docs: Add development instance setup

### PR DESCRIPTION
**Pull request by satvik2131**

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]
Btw you don't need to create new PRs, you can just amend the commit and force push it.

**Comment by provokateurin** [comment]
You need to fix the DCO by running `git commit --amend -s` and then `git push -f`

**Comment by satvik2131** [comment]
> You need to fix the DCO by running `git commit --amend -s` and then `git push -f`

done , please check

**Comment by provokateurin** [comment]
It's done automatically by the CI and it shows a green checkmark :)

**Comment by provokateurin** [comment]
Ah yeah your commit also needs to be GPG signed.

**Pull request merged**
