### PR TITLE
fix(neon): Fix SVG code compilation for web

### PR DESCRIPTION
**Pull request by provokateurin**
Extracted from https://github.com/nextcloud/neon/pull/372
This wasn't compiling before because it was relying on dart:io code internally.

### CODE REVIEW

**Review by Leptopoda — CHANGES_REQUESTED** [review]
From the SvgLoader documentation:
> /// A [BytesLoader] that parses a SVG data in an isolate and creates a
/// vector_graphics binary representation.

This means loading the file could happen in a separate isolate thus not blocking the main one.
I'd rather make a custom `UniversalSvgFileLoader` as each loader is only around 30 lines of code.

**Comment by provokateurin** [comment]
The annoying thing is that this code isn't even executed on web since we have no push notification support there. Maybe we should instead use a stub on web to fix the compilation (conditional import if you know what I mean).

**Comment by Leptopoda** [comment]
I don't know what makes most sense rn but this shouldn't even be a problem with #808.
Do you think it's worth stubbing?

**Comment by provokateurin** [comment]
I think I will go with the stub for now and once we have the plugin system we can easily drop it.

**Comment by provokateurin** [comment]
I went with your suggestion because creating the loader was very easy indeed. Just had to copy the SvgFileLoader and replace dart:io with universal_io.

**Review by Leptopoda — APPROVED** [review]

**Pull request merged**
