### PR TITLE
chore(release): publish packages

### PR DESCRIPTION
**Pull request by provokateurin**
- nextcloud@8.1.0

### CODE REVIEW

**Review by Leptopoda — APPROVED** [review]
I have to disagree with melos here, as this should be `8.0.2`

**Comment by provokateurin** [comment]
No it is correct due to https://github.com/nextcloud/neon/pull/2546

**Comment by Leptopoda** [comment]
Then let me correct myself. I disagree with the commit type used back then as it's a tooling change and doesn't add any functionality to the released package.

**Comment by provokateurin** [comment]
Yes, that's what I thought as well when I saw the bump. I'll be more careful next time :+1:

**Pull request merged**
