### PR TITLE
refactor l10n handling

### PR DESCRIPTION
**Pull request by Leptopoda**
In order to have common strings that can be reused and exported by the framework we need to have unique L10n classes.

As discussed at the conf.
The reuse of strings is needed for the work I'm doing on #535

### CODE REVIEW

**Review by provokateurin — CHANGES_REQUESTED** [review]
The classes should be named `Localizations` instead of `L10n`.
Other than that everything LGTM!

**Comment by Leptopoda** [comment]
Why not L10n?
I quite like the shorter name.

Should we now also drop the format check commit hook? It just makes commits slower and with autoformat turned on in the IDE this shouldn't happen as freequent.

**Comment by provokateurin** [comment]
For me L10n looks just ugly, but I also don't see a reason why we shouldn't just use the full name

**Comment by Leptopoda** [comment]
> Yeah I also don't like the format-check hook, but you wanted to have it because you often forgot to format before pushing.

Ok then I'll remove it as the auto generation of the l10n won't happen anymore (it just broke with the changes and we have the melos command for that)

**Pull request merged**
