### PR TITLE
refactor(neon_http_client): use nextcloud csrf request

### PR DESCRIPTION
**Pull request by Leptopoda**
some housekeeping to use and test the now documented csrf endpoint

### CODE REVIEW

**Comment by provokateurin** [comment]
Why are you splitting the logic for vm and web and basically making vm noop? IMO we should use the same logic regardless of the target. In this case it only increases code complexity while having not much benefits.
The other two commits LGTM.

**Comment by Leptopoda** [comment]
We already had this split logic (it was just in a single class).
I found it less complex to split it into two separate classes, as there is only one condition being made.

I also find the unit tests more readable now that they are split.
The new solution will also avoid creating the nextcloud client on io as it isn't even needed (no real impact but cleaner nevertheless).

I can drop the commit if you prefer to keep it unified.

**Comment by provokateurin** [comment]
Instead of having two implementations I would rather just not add it on vm.
Everything else can stay the same then.

**Comment by Leptopoda** [comment]
I unified the csrf logic as previously discussed in our call.
I also changed the fixture validation so we also get one for the csrf test.

**Review by provokateurin — APPROVED** [review]

**Comment by Leptopoda** [comment]
I'll change the webdav csrf interceptor (in the nc package) as a followup

**Pull request merged**
