### PR TITLE
feat(neon_framework)!: encrypt storages as sqlcypher databases

### PR DESCRIPTION
**Pull request by Leptopoda**
fixes: #1538, #1280

While sqlcipher supports migrating unencrypted databases I did not consider it in the scope of this PR.
We would need to create a ne db file and then migrate ...
Please make sure to remove the old cache as the DB might otherwise throw.
I also suggest cleaning your build cache with something like `melos exec flutter clean` as otherwise cmake might fail.

 I've tested it on both linux and android but only verified on linux that the db is actually encrypted.

### CODE REVIEW

**Comment by Leptopoda** [comment]
Making a draft so I don't  forget to add unit/integration tests.

**Review by provokateurin — COMMENTED** [review]
I didn't have a complete look at everything, but it looks pretty good to me (will do a proper review once the other PR is merged).

Will this affect the build size of the app?
Is there any way the request cache and sql persistence could share more logic? currently they are quite similar which is not great.

**Comment by Leptopoda** [comment]
> Will this affect the build size of the app?

probably; tests coming
I'll also verify encryption is working on android as you have suggested.

> Is there any way the request cache and sql persistence could share more logic?

I don't think there is anything they can really share. It's only the init method that is similar while every other is implementation specific. I might reconsider moving the database creation outside of the init method so other persistences can use the same db (thinking of the cookies which should be stored with the cache).

Other than that I don't think we can do anything here.

**Comment by Leptopoda** [comment]
Ok I was able to confirm that the DB is also encrypted on android.
The apk size increase is arround 20MB for the universal build (78.9MB => 100MB). I don't think there is anything we can do about this.

**Comment by Leptopoda** [comment]
Closing as we decided that the added encryption is not worth the bundle size increase.
Adding it in is trivial so open an issue if you need this functionality.

**Pull request closed without merging**
