### PR TITLE
[Feature][#921] dependency_validator added

### LINKED ISSUE #921: Setup CI for checking unused dependencies
https://pub.dev/packages/dependency_validator

### PR DESCRIPTION
**Pull request by NishchayShakya1**
# Description
A dependency validator is added to automatically check unused dependencies.

closes #921 
`hacktoberfest`

### CODE REVIEW

**Comment by provokateurin** [comment]
@Leptopoda should we add it to our global workspace package or rather to each package individually? I think both would work for us

**Comment by NishchayShakya1** [comment]
> @Leptopoda should we add it to our global workspace package or rather to each package individually? I think both would work for us

Yes, both will work

**Comment by provokateurin** [comment]
It was more of a architecture question than a technical one. Of course we can add it to each package, but the question is if we want to do it that way.

**Comment by NishchayShakya1** [comment]
> It was more of a architecture question than a technical one. Of course we can add it to each package, but the question is if we want to do it that way.

I think adding to each package will be better.

**Comment by provokateurin** [comment]
@Leptopoda Agreed with your points, I thought the same.

**Comment by provokateurin** [comment]
@NishchayShakya1 Would it be possible for you to incorporate the feedback? We can help you if you get stuck or don't know what to do.

**Comment by Leptopoda** [comment]
@NishchayShakya1 Are you still planning to implement this feature?
If you need any help feel free to ask.

Otherwise I'm going to close this one at the end of next week.

**Pull request closed without merging**
