### PR TITLE
fix(neon,neon_files,neon_news,neon_notes): Fix notch clipping content

### PR DESCRIPTION
**Pull request by provokateurin**
Fixes https://github.com/nextcloud/neon/issues/294
I tested with both the normal drawer and the always visible one and both work with this in portrait and landscape mode.

### CODE REVIEW

**Comment by Leptopoda** [comment]
This does not fix the issue for other pages like the settings or the file info where it's fairly noticeable

**Comment by provokateurin** [comment]
Ah I only fixed it for the main page because of the screenshot in the issue. I'll look into the other pages as well.

**Comment by Leptopoda** [comment]
I'm not sure it'll work but maybe we can just wrap the entire material app with a safe area :thinking:

**Comment by provokateurin** [comment]
The problem is that then the status bar will be just black. We can do it, but apps usually don't do it.

**Comment by Leptopoda** [comment]
Thinking about it some clients might want to display something full screen.
Like the video feed of talk in a call.

Maybe we can create a custom go_route like `SafeAreaRoute` that wraps the given page in a safe area?

**Comment by provokateurin** [comment]
For other pages than those displayed in home we need to individually add the SafeArea. In Talk for example the call is on a new page that isn't rendered inside the home page, so there it wouldn't matter. I think we can just add the SafeArea to all the pages that need it and then we are good.

**Comment by provokateurin** [comment]
@Leptopoda Please review again

**Review by Leptopoda — APPROVED** [review]
We should've done this earlier.
Such an easy fix xD

**Pull request merged**
